package net.sjhub.simplebikes.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMachbike extends ModelBase {
   ModelRenderer frame10;
   ModelRenderer frame9;
   ModelRenderer frame1;
   ModelRenderer seatR;
   ModelRenderer seatF;
   ModelRenderer frame2R;
   ModelRenderer frame5;
   ModelRenderer frame4;
   ModelRenderer frame3;
   ModelRenderer frame2;
   ModelRenderer frontbreaks;
   ModelRenderer chain1;
   ModelRenderer chain2;
   ModelRenderer frame8L;
   ModelRenderer frame6R;
   ModelRenderer frame7R;
   ModelRenderer seatL;
   ModelRenderer back_breaks;
   ModelRenderer frame6L;
   ModelRenderer frame7L;
   ModelRenderer handlebarmiddle;
   ModelRenderer handleparsplit;
   ModelRenderer breaksL;
   ModelRenderer pokeballthingyL;
   ModelRenderer handlegrip1L;
   ModelRenderer handlegrip5L;
   ModelRenderer handelbarR;
   ModelRenderer handelbartop;
   ModelRenderer arm1R;
   ModelRenderer handelbarL;
   ModelRenderer arm1L;
   ModelRenderer handlegrip2L;
   ModelRenderer handlegrip3L;
   ModelRenderer handlegrip4L;
   ModelRenderer handlegrip1R;
   ModelRenderer handlegrip2R;
   ModelRenderer handlegrip3R;
   ModelRenderer handlegrip4R;
   ModelRenderer handlegrip5R;
   ModelRenderer pokeballthingyR;
   ModelRenderer breaksR;
   ModelRenderer tire1F;
   ModelRenderer tire2F;
   ModelRenderer tire3F;
   ModelRenderer tire4F;
   ModelRenderer tire5F;
   ModelRenderer tire6F;
   ModelRenderer tire7F;
   ModelRenderer tire8F;
   ModelRenderer wheel_axelF;
   ModelRenderer spokesF;
   ModelRenderer biggear;
   ModelRenderer peddelAxel;
   ModelRenderer peddlearmR;
   ModelRenderer PeddleR;
   ModelRenderer peddlearmL;
   ModelRenderer PeddleL;
   ModelRenderer tire1B;
   ModelRenderer tire2B;
   ModelRenderer tire3B;
   ModelRenderer tire4B;
   ModelRenderer tire5B;
   ModelRenderer tire6B;
   ModelRenderer tire7B;
   ModelRenderer tire8B;
   ModelRenderer wheel_axelB;
   ModelRenderer spokesB;
   ModelRenderer frontTire;
   ModelRenderer rearTire;
   ModelRenderer peddleAssembly;
   ModelRenderer handleAssembly;

   public ModelMachbike() {
      this.textureWidth = 128;
      this.textureHeight = 64;
      this.frame10 = new ModelRenderer(this, 0, 47);
      this.frame10.addBox(-2.0F, 13.0F, -1.5F, 4, 3, 3);
      this.frame10.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame10.setTextureSize(128, 64);
      this.frame10.mirror = true;
      this.setRotation(this.frame10, 0.0F, 0.0F, 0.0F);
      this.frame9 = new ModelRenderer(this, 46, 18);
      this.frame9.addBox(-0.5F, -1.0F, 2.0F, 1, 2, 1);
      this.frame9.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame9.setTextureSize(128, 64);
      this.frame9.mirror = true;
      this.setRotation(this.frame9, -0.1396263F, 0.0F, 0.0F);
      this.frame1 = new ModelRenderer(this, 0, 20);
      this.frame1.addBox(-1.5F, 3.0F, -9.0F, 3, 4, 3);
      this.frame1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame1.setTextureSize(128, 64);
      this.frame1.mirror = true;
      this.setRotation(this.frame1, -0.2617994F, 0.0F, 0.0F);
      this.seatR = new ModelRenderer(this, 24, 10);
      this.seatR.addBox(-1.0F, -1.0F, 1.0F, 2, 2, 5);
      this.seatR.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.seatR.setTextureSize(128, 64);
      this.seatR.mirror = true;
      this.setRotation(this.seatR, 0.2617994F, -0.1570796F, 0.0F);
      this.seatF = new ModelRenderer(this, 0, 11);
      this.seatF.addBox(-1.0F, -1.2F, -1.0F, 2, 2, 3);
      this.seatF.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.seatF.setTextureSize(128, 64);
      this.seatF.mirror = true;
      this.setRotation(this.seatF, 0.0F, 0.0F, 0.0F);
      this.frame2R = new ModelRenderer(this, 27, 43);
      this.frame2R.addBox(-3.0F, 14.0F, 12.0F, 2, 2, 2);
      this.frame2R.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame2R.setTextureSize(128, 64);
      this.frame2R.mirror = true;
      this.setRotation(this.frame2R, 0.0F, 0.0F, 0.0F);
      this.frame5 = new ModelRenderer(this, 42, 39);
      this.frame5.addBox(-1.0F, 0.0F, 4.0F, 2, 1, 6);
      this.frame5.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame5.setTextureSize(128, 64);
      this.frame5.mirror = true;
      this.setRotation(this.frame5, -0.8203047F, 0.0F, 0.0F);
      this.frame4 = new ModelRenderer(this, 38, 17);
      this.frame4.addBox(-1.0F, 1.0F, 1.5F, 2, 14, 2);
      this.frame4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame4.setTextureSize(128, 64);
      this.frame4.mirror = true;
      this.setRotation(this.frame4, -0.1396263F, 0.0F, 0.0F);
      this.frame3 = new ModelRenderer(this, 0, 25);
      this.frame3.addBox(-1.0F, 7.0F, -1.0F, 2, 2, 14);
      this.frame3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame3.setTextureSize(128, 64);
      this.frame3.mirror = true;
      this.setRotation(this.frame3, -1.064651F, 0.0F, 0.0F);
      this.frame2 = new ModelRenderer(this, 21, 25);
      this.frame2.addBox(-1.0F, 2.0F, -7.0F, 2, 2, 9);
      this.frame2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame2.setTextureSize(128, 64);
      this.frame2.mirror = true;
      this.setRotation(this.frame2, -0.0872665F, 0.0F, 0.0F);
      this.frontbreaks = new ModelRenderer(this, 52, 41);
      this.frontbreaks.addBox(-2.0F, 10.0F, -9.0F, 4, 2, 1);
      this.frontbreaks.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frontbreaks.setTextureSize(128, 64);
      this.frontbreaks.mirror = true;
      this.setRotation(this.frontbreaks, -0.3490659F, 0.0F, 0.0F);
      this.chain1 = new ModelRenderer(this, 34, 0);
      this.chain1.addBox(-1.9F, 11.5F, 4.5F, 1, 1, 11);
      this.chain1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.chain1.setTextureSize(128, 64);
      this.chain1.mirror = true;
      this.setRotation(this.chain1, -0.1745329F, 0.0F, 0.0F);
      this.chain2 = new ModelRenderer(this, 38, 0);
      this.chain2.addBox(-1.9F, 15.7F, -2.0F, 1, 1, 11);
      this.chain2.setRotationPoint(0.0F, 0.0F, 3.0F);
      this.chain2.setTextureSize(128, 64);
      this.chain2.mirror = true;
      this.setRotation(this.chain2, 0.0698132F, 0.0F, 0.0F);
      this.frame8L = new ModelRenderer(this, 27, 43);
      this.frame8L.addBox(1.0F, 14.0F, 12.0F, 2, 2, 2);
      this.frame8L.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame8L.setTextureSize(128, 64);
      this.frame8L.mirror = true;
      this.setRotation(this.frame8L, 0.0F, 0.0F, 0.0F);
      this.frame6R = new ModelRenderer(this, 25, 41);
      this.frame6R.addBox(-2.0F, 0.0F, 9.0F, 1, 1, 11);
      this.frame6R.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame6R.setTextureSize(128, 64);
      this.frame6R.mirror = true;
      this.setRotation(this.frame6R, -0.8203047F, 0.0F, 0.0F);
      this.frame7R = new ModelRenderer(this, 6, 42);
      this.frame7R.addBox(-2.0F, 15.0F, 1.0F, 1, 1, 11);
      this.frame7R.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame7R.setTextureSize(128, 64);
      this.frame7R.mirror = true;
      this.setRotation(this.frame7R, 0.0F, 0.0F, 0.0F);
      this.seatL = new ModelRenderer(this, 10, 10);
      this.seatL.addBox(-1.0F, -1.0F, 1.0F, 2, 2, 5);
      this.seatL.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.seatL.setTextureSize(128, 64);
      this.seatL.mirror = true;
      this.setRotation(this.seatL, 0.2617994F, 0.1570796F, 0.0F);
      this.back_breaks = new ModelRenderer(this, 52, 41);
      this.back_breaks.addBox(-2.0F, 11.0F, 1.0F, 4, 2, 1);
      this.back_breaks.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.back_breaks.setTextureSize(128, 64);
      this.back_breaks.mirror = true;
      this.setRotation(this.back_breaks, 0.715585F, 0.0F, 0.0F);
      this.frame6L = new ModelRenderer(this, 25, 41);
      this.frame6L.addBox(1.0F, 0.0F, 9.0F, 1, 1, 11);
      this.frame6L.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame6L.setTextureSize(128, 64);
      this.frame6L.mirror = true;
      this.setRotation(this.frame6L, -0.8203047F, 0.0F, 0.0F);
      this.frame7L = new ModelRenderer(this, 6, 42);
      this.frame7L.addBox(1.0F, 15.0F, 1.0F, 1, 1, 11);
      this.frame7L.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame7L.setTextureSize(128, 64);
      this.frame7L.mirror = true;
      this.setRotation(this.frame7L, 0.0F, 0.0F, 0.0F);
      this.handleAssembly = new ModelRenderer(this);
      this.handleAssembly.setRotationPoint(0.0F, 3.0F, -8.5F);
      this.handlebarmiddle = new ModelRenderer(this, 70, 18);
      this.handlebarmiddle.addBox(-1.0F, -4.0F, -1.0F, 2, 7, 2);
      this.handleAssembly.addChild(this.handlebarmiddle);
      this.handlebarmiddle.setTextureSize(128, 64);
      this.handlebarmiddle.mirror = true;
      this.setRotation(this.handlebarmiddle, -0.2617994F, 0.0F, 0.0F);
      this.handleparsplit = new ModelRenderer(this, 70, 27);
      this.handleparsplit.addBox(-2.0F, 3.0F, -1.0F, 4, 1, 2);
      this.handleAssembly.addChild(this.handleparsplit);
      this.handleparsplit.setTextureSize(128, 64);
      this.handleparsplit.mirror = true;
      this.setRotation(this.handleparsplit, -0.2617994F, 0.0F, 0.0F);
      this.breaksL = new ModelRenderer(this, 84, 4);
      this.breaksL.addBox(5.0F, -1.5F, -7.0F, 1, 4, 1);
      this.handleAssembly.addChild(this.breaksL);
      this.breaksL.setTextureSize(128, 64);
      this.breaksL.mirror = true;
      this.setRotation(this.breaksL, -0.6632251F, 0.0F, 0.0F);
      this.pokeballthingyL = new ModelRenderer(this, 82, 0);
      this.pokeballthingyL.addBox(4.4F, -4.0F, -7.0F, 2, 2, 1);
      this.handleAssembly.addChild(this.pokeballthingyL);
      this.pokeballthingyL.setTextureSize(128, 64);
      this.pokeballthingyL.mirror = true;
      this.setRotation(this.pokeballthingyL, -0.5061455F, 0.0F, 0.0F);
      this.handlegrip1L = new ModelRenderer(this, 70, 8);
      this.handlegrip1L.addBox(3.5F, -5.5F, 0.0F, 3, 2, 2);
      this.handleAssembly.addChild(this.handlegrip1L);
      this.handlegrip1L.setTextureSize(128, 64);
      this.handlegrip1L.mirror = true;
      this.setRotation(this.handlegrip1L, 0.0F, 0.5235988F, 0.0F);
      this.handlegrip5L = new ModelRenderer(this, 70, 12);
      this.handlegrip5L.addBox(4.5F, -2.2F, -4.3F, 2, 2, 4);
      this.handleAssembly.addChild(this.handlegrip5L);
      this.handlegrip5L.setTextureSize(128, 64);
      this.handlegrip5L.mirror = true;
      this.setRotation(this.handlegrip5L, -0.1745329F, 0.0F, 0.0F);
      this.handelbarR = new ModelRenderer(this, 70, 4);
      this.handelbarR.addBox(-4.0F, -5.5F, -1.5F, 3, 2, 2);
      this.handleAssembly.addChild(this.handelbarR);
      this.handelbarR.setTextureSize(128, 64);
      this.handelbarR.mirror = true;
      this.setRotation(this.handelbarR, 0.0F, 0.0F, 0.0F);
      this.handelbartop = new ModelRenderer(this, 80, 10);
      this.handelbartop.addBox(-2.0F, -5.0F, -1.0F, 4, 2, 2);
      this.handleAssembly.addChild(this.handelbartop);
      this.handelbartop.setTextureSize(128, 64);
      this.handelbartop.mirror = true;
      this.setRotation(this.handelbartop, 0.0F, 0.0F, 0.0F);
      this.arm1R = new ModelRenderer(this, 70, 30);
      this.arm1R.addBox(-2.0F, 4.0F, -1.0F, 1, 9, 2);
      this.handleAssembly.addChild(this.arm1R);
      this.arm1R.setTextureSize(128, 64);
      this.arm1R.mirror = true;
      this.setRotation(this.arm1R, -0.2617994F, 0.0F, 0.0F);
      this.handelbarL = new ModelRenderer(this, 70, 4);
      this.handelbarL.mirror = true;
      this.handelbarL.addBox(1.0F, -5.5F, -1.5F, 3, 2, 2);
      this.handleAssembly.addChild(this.handelbarL);
      this.handelbarL.setTextureSize(128, 64);
      this.handelbarL.mirror = true;
      this.setRotation(this.handelbarL, 0.0F, 0.0F, 0.0F);
      this.handelbarL.mirror = false;
      this.arm1L = new ModelRenderer(this, 70, 30);
      this.arm1L.addBox(1.0F, 4.0F, -1.0F, 1, 9, 2);
      this.handleAssembly.addChild(this.arm1L);
      this.arm1L.setTextureSize(128, 64);
      this.arm1L.mirror = true;
      this.setRotation(this.arm1L, -0.2617994F, 0.0F, 0.0F);
      this.handlegrip2L = new ModelRenderer(this, 70, 0);
      this.handlegrip2L.addBox(4.5F, -6.3F, -1.5F, 2, 2, 2);
      this.handleAssembly.addChild(this.handlegrip2L);
      this.handlegrip2L.setTextureSize(128, 64);
      this.handlegrip2L.mirror = true;
      this.setRotation(this.handlegrip2L, 0.5235988F, 0.0F, 0.0F);
      this.handlegrip3L = new ModelRenderer(this, 70, 0);
      this.handlegrip3L.addBox(4.5F, -3.5F, -5.4F, 2, 2, 2);
      this.handleAssembly.addChild(this.handlegrip3L);
      this.handlegrip3L.setTextureSize(128, 64);
      this.handlegrip3L.mirror = true;
      this.setRotation(this.handlegrip3L, -0.2443461F, 0.0F, 0.0F);
      this.handlegrip4L = new ModelRenderer(this, 70, 0);
      this.handlegrip4L.addBox(4.5F, -3.8F, -4.1F, 2, 2, 2);
      this.handleAssembly.addChild(this.handlegrip4L);
      this.handlegrip4L.setTextureSize(128, 64);
      this.handlegrip4L.mirror = true;
      this.setRotation(this.handlegrip4L, 0.2094395F, 0.0F, 0.0F);
      this.handlegrip1R = new ModelRenderer(this, 70, 8);
      this.handlegrip1R.addBox(-6.5F, -5.5F, 0.0F, 3, 2, 2);
      this.handleAssembly.addChild(this.handlegrip1R);
      this.handlegrip1R.setTextureSize(128, 64);
      this.handlegrip1R.mirror = true;
      this.setRotation(this.handlegrip1R, 0.0F, -0.5235988F, 0.0F);
      this.handlegrip2R = new ModelRenderer(this, 70, 0);
      this.handlegrip2R.addBox(-6.5F, -6.3F, -1.5F, 2, 2, 2);
      this.handleAssembly.addChild(this.handlegrip2R);
      this.handlegrip2R.setTextureSize(128, 64);
      this.handlegrip2R.mirror = true;
      this.setRotation(this.handlegrip2R, 0.5235988F, 0.0F, 0.0F);
      this.handlegrip3R = new ModelRenderer(this, 70, 0);
      this.handlegrip3R.addBox(-6.5F, -3.5F, -5.4F, 2, 2, 2);
      this.handleAssembly.addChild(this.handlegrip3R);
      this.handlegrip3R.setTextureSize(128, 64);
      this.handlegrip3R.mirror = true;
      this.setRotation(this.handlegrip3R, -0.2443461F, 0.0F, 0.0F);
      this.handlegrip4R = new ModelRenderer(this, 70, 0);
      this.handlegrip4R.addBox(-6.5F, -3.8F, -4.1F, 2, 2, 2);
      this.handleAssembly.addChild(this.handlegrip4R);
      this.handlegrip4R.setTextureSize(128, 64);
      this.handlegrip4R.mirror = true;
      this.setRotation(this.handlegrip4R, 0.2094395F, 0.0F, 0.0F);
      this.handlegrip5R = new ModelRenderer(this, 70, 12);
      this.handlegrip5R.addBox(-6.5F, -2.2F, -4.3F, 2, 2, 4);
      this.handleAssembly.addChild(this.handlegrip5R);
      this.handlegrip5R.setTextureSize(128, 64);
      this.handlegrip5R.mirror = true;
      this.setRotation(this.handlegrip5R, -0.1745329F, 0.0F, 0.0F);
      this.pokeballthingyR = new ModelRenderer(this, 82, 0);
      this.pokeballthingyR.addBox(-6.4F, -4.0F, -7.0F, 2, 2, 1);
      this.handleAssembly.addChild(this.pokeballthingyR);
      this.pokeballthingyR.setTextureSize(128, 64);
      this.pokeballthingyR.mirror = true;
      this.setRotation(this.pokeballthingyR, -0.5061455F, 0.0F, 0.0F);
      this.breaksR = new ModelRenderer(this, 84, 4);
      this.breaksR.addBox(-6.0F, -1.5F, -7.0F, 1, 4, 1);
      this.handleAssembly.addChild(this.breaksR);
      this.breaksR.setTextureSize(128, 64);
      this.breaksR.mirror = true;
      this.wheel_axelF = new ModelRenderer(this, 95, 35);
      this.wheel_axelF.addBox(-2.5F, -0.5F, -0.5F, 5, 1, 1);
      this.handleAssembly.addChild(this.wheel_axelF);
      this.wheel_axelF.setRotationPoint(0.0F, 12.0F, -3.5F);
      this.wheel_axelF.setTextureSize(128, 64);
      this.setRotation(this.wheel_axelF, 0.0F, 0.0F, 0.0F);
      this.setRotation(this.breaksR, -0.6632251F, 0.0F, 0.0F);
      this.frontTire = new ModelRenderer(this);
      this.frontTire.setRotationPoint(0.0F, 12.0F, -3.5F);
      this.tire1F = new ModelRenderer(this, 95, 0);
      this.tire1F.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.tire1F.setTextureSize(128, 64);
      this.setRotation(this.tire1F, 0.0F, 0.0F, 0.0F);
      this.frontTire.addChild(this.tire1F);
      this.tire2F = new ModelRenderer(this, 95, 0);
      this.tire2F.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.tire2F.setTextureSize(128, 64);
      this.setRotation(this.tire2F, 0.7853982F, 0.0F, 0.0F);
      this.frontTire.addChild(this.tire2F);
      this.tire3F = new ModelRenderer(this, 95, 0);
      this.tire3F.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.tire3F.setTextureSize(128, 64);
      this.setRotation(this.tire3F, 1.570796F, 0.0F, 0.0F);
      this.frontTire.addChild(this.tire3F);
      this.tire4F = new ModelRenderer(this, 95, 0);
      this.tire4F.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.tire4F.setTextureSize(128, 64);
      this.setRotation(this.tire4F, 2.356194F, 0.0F, 0.0F);
      this.frontTire.addChild(this.tire4F);
      this.tire5F = new ModelRenderer(this, 95, 0);
      this.tire5F.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.tire5F.setTextureSize(128, 64);
      this.setRotation(this.tire5F, 3.141593F, 0.0F, 0.0F);
      this.frontTire.addChild(this.tire5F);
      this.tire6F = new ModelRenderer(this, 95, 0);
      this.tire6F.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.tire6F.setTextureSize(128, 64);
      this.setRotation(this.tire6F, -2.356194F, 0.0F, 0.0F);
      this.frontTire.addChild(this.tire6F);
      this.tire7F = new ModelRenderer(this, 95, 0);
      this.tire7F.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.tire7F.setTextureSize(128, 64);
      this.setRotation(this.tire7F, -1.570796F, 0.0F, 0.0F);
      this.frontTire.addChild(this.tire7F);
      this.tire8F = new ModelRenderer(this, 95, 0);
      this.tire8F.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.tire8F.setTextureSize(128, 64);
      this.setRotation(this.tire8F, -0.7853982F, 0.0F, 0.0F);
      this.frontTire.addChild(this.tire8F);
      this.spokesF = new ModelRenderer(this, 95, 9);
      this.spokesF.addBox(-0.5F, -6.5F, -6.5F, 1, 13, 13);
      this.spokesF.setTextureSize(128, 64);
      this.setRotation(this.spokesF, 0.0F, 0.0F, 0.0F);
      this.frontTire.addChild(this.spokesF);
      this.peddleAssembly = new ModelRenderer(this);
      this.peddleAssembly.setRotationPoint(0.0F, 14.5F, 0.0F);
      this.biggear = new ModelRenderer(this, 0, 0);
      this.biggear.addBox(-1.9F, -2.5F, -2.5F, 1, 5, 5);
      this.biggear.setTextureSize(128, 64);
      this.peddleAssembly.addChild(this.biggear);
      this.setRotation(this.biggear, 0.0F, 0.0F, 0.0F);
      this.peddelAxel = new ModelRenderer(this, 0, 43);
      this.peddelAxel.addBox(-3.0F, -1.0F, -1.0F, 6, 2, 2);
      this.peddleAssembly.addChild(this.peddelAxel);
      this.peddelAxel.setTextureSize(128, 64);
      this.peddelAxel.mirror = true;
      this.setRotation(this.peddelAxel, 0.0F, 0.0F, 0.0F);
      this.peddlearmR = new ModelRenderer(this, 14, 0);
      this.peddlearmR.addBox(-4.0F, -0.5F, -4.5F, 1, 1, 5);
      this.peddleAssembly.addChild(this.peddlearmR);
      this.peddlearmR.setTextureSize(128, 64);
      this.peddlearmR.mirror = true;
      this.setRotation(this.peddlearmR, -2.356194F, 0.0F, 0.0F);
      this.PeddleR = new ModelRenderer(this, 24, 0);
      this.PeddleR.addBox(-8.0F, -1.5F, -5.0F, 4, 3, 1);
      this.peddleAssembly.addChild(this.PeddleR);
      this.PeddleR.setTextureSize(128, 64);
      this.PeddleR.mirror = true;
      this.setRotation(this.PeddleR, -2.356194F, 0.0F, 0.0F);
      this.peddlearmL = new ModelRenderer(this, 14, 0);
      this.peddlearmL.addBox(3.0F, -0.5F, -4.5F, 1, 1, 5);
      this.peddleAssembly.addChild(this.peddlearmL);
      this.peddlearmL.setTextureSize(128, 64);
      this.peddlearmL.mirror = true;
      this.setRotation(this.peddlearmL, 0.7853982F, 0.0F, 0.0F);
      this.PeddleL = new ModelRenderer(this, 24, 0);
      this.PeddleL.addBox(4.0F, -1.5F, -5.0F, 4, 3, 1);
      this.peddleAssembly.addChild(this.PeddleL);
      this.PeddleL.setTextureSize(128, 64);
      this.PeddleL.mirror = true;
      this.setRotation(this.PeddleL, 0.7853982F, 0.0F, 0.0F);
      this.rearTire = new ModelRenderer(this);
      this.rearTire.setRotationPoint(0.0F, 15.0F, 13.0F);
      this.tire1B = new ModelRenderer(this, 95, 0);
      this.tire1B.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.rearTire.addChild(this.tire1B);
      this.tire1B.setTextureSize(128, 64);
      this.setRotation(this.tire1B, 0.0F, 0.0F, 0.0F);
      this.tire2B = new ModelRenderer(this, 95, 0);
      this.tire2B.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.rearTire.addChild(this.tire2B);
      this.tire2B.setTextureSize(128, 64);
      this.setRotation(this.tire2B, 0.7853982F, 0.0F, 0.0F);
      this.tire3B = new ModelRenderer(this, 95, 0);
      this.tire3B.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.rearTire.addChild(this.tire3B);
      this.tire3B.setTextureSize(128, 64);
      this.setRotation(this.tire3B, 1.570796F, 0.0F, 0.0F);
      this.tire4B = new ModelRenderer(this, 95, 0);
      this.tire4B.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.rearTire.addChild(this.tire4B);
      this.tire4B.setTextureSize(128, 64);
      this.setRotation(this.tire4B, 2.356194F, 0.0F, 0.0F);
      this.tire5B = new ModelRenderer(this, 95, 0);
      this.tire5B.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.rearTire.addChild(this.tire5B);
      this.tire5B.setTextureSize(128, 64);
      this.setRotation(this.tire5B, 3.141593F, 0.0F, 0.0F);
      this.tire6B = new ModelRenderer(this, 95, 0);
      this.tire6B.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.rearTire.addChild(this.tire6B);
      this.tire6B.setTextureSize(128, 64);
      this.setRotation(this.tire6B, -2.356194F, 0.0F, 0.0F);
      this.tire7B = new ModelRenderer(this, 95, 0);
      this.tire7B.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.rearTire.addChild(this.tire7B);
      this.tire7B.setTextureSize(128, 64);
      this.setRotation(this.tire7B, -1.570796F, 0.0F, 0.0F);
      this.tire8B = new ModelRenderer(this, 95, 0);
      this.tire8B.addBox(-1.0F, -8.0F, -3.5F, 2, 2, 7);
      this.rearTire.addChild(this.tire8B);
      this.tire8B.setTextureSize(128, 64);
      this.setRotation(this.tire8B, -0.7853982F, 0.0F, 0.0F);
      this.spokesB = new ModelRenderer(this, 95, 9);
      this.spokesB.addBox(-0.5F, -6.5F, -6.5F, 1, 13, 13);
      this.rearTire.addChild(this.spokesB);
      this.spokesB.setTextureSize(128, 64);
      this.setRotation(this.spokesB, 0.0F, 0.0F, 0.0F);
      this.wheel_axelB = new ModelRenderer(this, 95, 35);
      this.wheel_axelB.addBox(-2.5F, -0.5F, -0.5F, 5, 1, 1);
      this.wheel_axelB.setRotationPoint(0.0F, 15.0F, 13.0F);
      this.wheel_axelB.setTextureSize(128, 64);
      this.wheel_axelB.mirror = true;
      this.setRotation(this.wheel_axelB, 0.0F, 0.0F, 0.0F);
      this.handleAssembly.addChild(this.frontTire);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.frame10.render(f5);
      this.frame9.render(f5);
      this.frame1.render(f5);
      this.seatR.render(f5);
      this.seatF.render(f5);
      this.frame2R.render(f5);
      this.frame5.render(f5);
      this.frame4.render(f5);
      this.frame3.render(f5);
      this.frame2.render(f5);
      this.frontbreaks.render(f5);
      this.chain1.render(f5);
      this.chain2.render(f5);
      this.frame8L.render(f5);
      this.frame6R.render(f5);
      this.frame7R.render(f5);
      this.seatL.render(f5);
      this.back_breaks.render(f5);
      this.frame6L.render(f5);
      this.frame7L.render(f5);
      this.handleAssembly.render(f5);
      this.peddleAssembly.render(f5);
      this.rearTire.render(f5);
      this.wheel_axelB.render(f5);
   }

   private void setRotation(ModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }

   public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity entity) {
      super.setRotationAngles(par1, par2, par3, par4, par5, par6, entity);
   }
}
