package net.sjhub.simplebikes.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.sjhub.simplebikes.registry.bikes.acrobike.entities.EntityAcrobike;

import java.util.Iterator;

public class ModelAcrobike extends ModelBase {
   ModelRenderer frame1;
   ModelRenderer seatR;
   ModelRenderer seatF;
   ModelRenderer frame2R;
   ModelRenderer frame3;
   ModelRenderer frame4R;
   ModelRenderer frame5R;
   ModelRenderer frame6;
   ModelRenderer frame7;
   ModelRenderer frame8;
   ModelRenderer frame9;
   ModelRenderer frame10;
   ModelRenderer frame11;
   ModelRenderer frame12;
   ModelRenderer chain1;
   ModelRenderer chain2;
   ModelRenderer frame2L;
   ModelRenderer frame4L;
   ModelRenderer frame5L;
   ModelRenderer seatL;
   ModelRenderer handlebarmiddle;
   ModelRenderer handleparsplit;
   ModelRenderer breaksR;
   ModelRenderer pokeballthingy;
   ModelRenderer handlegrip1R;
   ModelRenderer handlegrip2R;
   ModelRenderer handelbarR;
   ModelRenderer handelbartop;
   ModelRenderer arm3R;
   ModelRenderer arm1R;
   ModelRenderer arm2R;
   ModelRenderer handelbarL;
   ModelRenderer handlegrip1L;
   ModelRenderer handlegrip2L;
   ModelRenderer breaksL;
   ModelRenderer arm1L;
   ModelRenderer arm2L;
   ModelRenderer arm3L;
   ModelRenderer tire1F;
   ModelRenderer tire2F;
   ModelRenderer tire3F;
   ModelRenderer tire4F;
   ModelRenderer tire5F;
   ModelRenderer tire6F;
   ModelRenderer tire7F;
   ModelRenderer tire8F;
   ModelRenderer wheel_axelF;
   ModelRenderer spokesF;
   ModelRenderer biggear;
   ModelRenderer Shape27;
   ModelRenderer peddlearm1;
   ModelRenderer peddlearm2;
   ModelRenderer Peddle1;
   ModelRenderer Peddle2;
   ModelRenderer tire1B;
   ModelRenderer tire2B;
   ModelRenderer tire3B;
   ModelRenderer tire4B;
   ModelRenderer tire5B;
   ModelRenderer tire6B;
   ModelRenderer tire7B;
   ModelRenderer tire8B;
   ModelRenderer wheel_axelB;
   ModelRenderer spokesB;
   ModelRenderer handleAssembly;
   ModelRenderer pedalAssembly;
   ModelRenderer frontTire;
   ModelRenderer rearTire;

   public ModelAcrobike() {
      this.textureWidth = 128;
      this.textureHeight = 64;
      this.frontTire = new ModelRenderer(this);
      this.rearTire = new ModelRenderer(this);
      this.frame1 = new ModelRenderer(this, 0, 20);
      this.frame1.addBox(-1.5F, 3.0F, -10.0F, 3, 2, 3);
      this.frame1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame1.setTextureSize(128, 64);
      this.frame1.mirror = true;
      this.setRotation(this.frame1, 0.0F, 0.0F, 0.0F);
      this.seatR = new ModelRenderer(this, 40, 8);
      this.seatR.mirror = true;
      this.seatR.addBox(-1.0F, 2.0F, 1.0F, 2, 2, 5);
      this.seatR.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.seatR.setTextureSize(128, 64);
      this.seatR.mirror = true;
      this.setRotation(this.seatR, 0.2617994F, -0.1570796F, 0.0F);
      this.seatR.mirror = false;
      this.seatF = new ModelRenderer(this, 30, 10);
      this.seatF.addBox(-1.0F, 1.8F, -1.0F, 2, 2, 3);
      this.seatF.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.seatF.setTextureSize(128, 64);
      this.seatF.mirror = true;
      this.setRotation(this.seatF, 0.0F, 0.0F, 0.0F);
      this.frame2R = new ModelRenderer(this, 27, 43);
      this.frame2R.addBox(-3.0F, 14.0F, 12.0F, 2, 2, 2);
      this.frame2R.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame2R.setTextureSize(128, 64);
      this.frame2R.mirror = true;
      this.setRotation(this.frame2R, 0.0F, 0.0F, 0.0F);
      this.frame3 = new ModelRenderer(this, 42, 39);
      this.frame3.addBox(-1.0F, 9.5F, 6.0F, 2, 1, 1);
      this.frame3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame3.setTextureSize(128, 64);
      this.frame3.mirror = true;
      this.setRotation(this.frame3, 0.0F, 0.0F, 0.0F);
      this.frame4R = new ModelRenderer(this, 36, 42);
      this.frame4R.addBox(-2.0F, 4.0F, 11.0F, 1, 1, 7);
      this.frame4R.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame4R.setTextureSize(128, 64);
      this.frame4R.mirror = true;
      this.setRotation(this.frame4R, -0.6108652F, 0.0F, 0.0F);
      this.frame5R = new ModelRenderer(this, 16, 43);
      this.frame5R.addBox(-2.0F, 15.0F, 5.0F, 1, 1, 7);
      this.frame5R.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame5R.setTextureSize(128, 64);
      this.frame5R.mirror = true;
      this.setRotation(this.frame5R, 0.0F, 0.0F, 0.0F);
      this.frame6 = new ModelRenderer(this, 36, 30);
      this.frame6.addBox(-0.5F, 9.5F, -1.0F, 1, 1, 7);
      this.frame6.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame6.setTextureSize(128, 64);
      this.frame6.mirror = true;
      this.setRotation(this.frame6, 0.0F, 0.0F, 0.0F);
      this.frame7 = new ModelRenderer(this, 38, 25);
      this.frame7.addBox(-1.0F, 9.0F, 1.0F, 2, 2, 3);
      this.frame7.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame7.setTextureSize(128, 64);
      this.frame7.mirror = true;
      this.setRotation(this.frame7, 0.0F, 0.0F, 0.0F);
      this.frame8 = new ModelRenderer(this, 38, 17);
      this.frame8.addBox(-1.0F, 3.0F, 1.5F, 2, 6, 2);
      this.frame8.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame8.setTextureSize(128, 64);
      this.frame8.mirror = true;
      this.setRotation(this.frame8, 0.0F, 0.0F, 0.0F);
      this.frame9 = new ModelRenderer(this, 22, 34);
      this.frame9.addBox(-1.5F, 5.5F, 1.0F, 3, 3, 3);
      this.frame9.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame9.setTextureSize(128, 64);
      this.frame9.mirror = true;
      this.setRotation(this.frame9, 0.0F, 0.0F, 0.0F);
      this.frame10 = new ModelRenderer(this, 0, 25);
      this.frame10.addBox(-1.0F, 7.0F, -3.0F, 2, 2, 16);
      this.frame10.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame10.setTextureSize(128, 64);
      this.frame10.mirror = true;
      this.setRotation(this.frame10, -0.7853982F, 0.0F, 0.0F);
      this.frame11 = new ModelRenderer(this, 21, 25);
      this.frame11.addBox(-1.0F, 6.0F, -5.0F, 2, 2, 6);
      this.frame11.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame11.setTextureSize(128, 64);
      this.frame11.mirror = true;
      this.setRotation(this.frame11, 0.0872665F, 0.0F, 0.0F);
      this.frame12 = new ModelRenderer(this, 52, 42);
      this.frame12.addBox(-2.0F, 7.0F, 12.5F, 4, 7, 1);
      this.frame12.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame12.setTextureSize(128, 64);
      this.frame12.mirror = true;
      this.setRotation(this.frame12, 0.0F, 0.0F, 0.0F);
      this.chain1 = new ModelRenderer(this, 34, 0);
      this.chain1.addBox(-1.9F, 10.0F, 9.0F, 1, 1, 7);
      this.chain1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.chain1.setTextureSize(128, 64);
      this.chain1.mirror = true;
      this.setRotation(this.chain1, -0.2617994F, 0.0F, 0.0F);
      this.chain2 = new ModelRenderer(this, 50, 0);
      this.chain2.addBox(-1.9F, 16.0F, 1.0F, 1, 1, 8);
      this.chain2.setRotationPoint(0.0F, 0.0F, 3.0F);
      this.chain2.setTextureSize(128, 64);
      this.chain2.mirror = true;
      this.setRotation(this.chain2, 0.0872665F, 0.0F, 0.0F);
      this.frame2L = new ModelRenderer(this, 27, 43);
      this.frame2L.mirror = true;
      this.frame2L.addBox(1.0F, 14.0F, 12.0F, 2, 2, 2);
      this.frame2L.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame2L.setTextureSize(128, 64);
      this.setRotation(this.frame2L, 0.0F, 0.0F, 0.0F);
      this.frame4L = new ModelRenderer(this, 36, 42);
      this.frame4L.mirror = true;
      this.frame4L.addBox(1.0F, 4.0F, 11.0F, 1, 1, 7);
      this.frame4L.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame4L.setTextureSize(128, 64);
      this.setRotation(this.frame4L, -0.6108652F, 0.0F, 0.0F);
      this.frame5L = new ModelRenderer(this, 16, 43);
      this.frame5L.mirror = true;
      this.frame5L.addBox(1.0F, 15.0F, 5.0F, 1, 1, 7);
      this.frame5L.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.frame5L.setTextureSize(128, 64);
      this.setRotation(this.frame5L, 0.0F, 0.0F, 0.0F);
      this.seatL = new ModelRenderer(this, 40, 8);
      this.seatL.mirror = true;
      this.seatL.addBox(-1.0F, 2.0F, 1.0F, 2, 2, 5);
      this.seatL.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.seatL.setTextureSize(128, 64);
      this.setRotation(this.seatL, 0.2617994F, 0.1570796F, 0.0F);
      this.handlebarmiddle = new ModelRenderer(this, 70, 14);
      this.handlebarmiddle.addBox(-1.0F, -2.0F, -1.0F, 2, 5, 2);
      this.handlebarmiddle.setTextureSize(128, 64);
      this.handlebarmiddle.mirror = true;
      this.setRotation(this.handlebarmiddle, 0.0F, 0.0F, 0.0F);
      this.handleparsplit = new ModelRenderer(this, 70, 21);
      this.handleparsplit.addBox(-2.5F, 3.0F, -1.0F, 5, 2, 2);
      this.handleparsplit.setTextureSize(128, 64);
      this.handleparsplit.mirror = true;
      this.setRotation(this.handleparsplit, 0.0F, 0.0F, 0.0F);
      this.breaksR = new ModelRenderer(this, 84, 0);
      this.breaksR.addBox(-9.0F, -2.5F, -1.5F, 4, 1, 1);
      this.breaksR.setTextureSize(128, 64);
      this.breaksR.mirror = true;
      this.setRotation(this.breaksR, 0.1745329F, 0.0F, 0.0F);
      this.pokeballthingy = new ModelRenderer(this, 82, 10);
      this.pokeballthingy.addBox(-1.0F, -4.0F, -3.0F, 2, 2, 1);
      this.pokeballthingy.setTextureSize(128, 64);
      this.pokeballthingy.mirror = true;
      this.setRotation(this.pokeballthingy, -0.3490659F, 0.0F, 0.0F);
      this.handlegrip1R = new ModelRenderer(this, 70, 4);
      this.handlegrip1R.addBox(-5.5F, -5.0F, -1.0F, 1, 3, 3);
      this.handlegrip1R.setTextureSize(128, 64);
      this.handlegrip1R.mirror = true;
      this.setRotation(this.handlegrip1R, 0.0F, 0.0F, 0.0F);
      this.handlegrip2R = new ModelRenderer(this, 70, 0);
      this.handlegrip2R.addBox(-10.5F, -4.5F, -0.5F, 5, 2, 2);
      this.handlegrip2R.setTextureSize(128, 64);
      this.handlegrip2R.mirror = true;
      this.setRotation(this.handlegrip2R, 0.0F, 0.0F, 0.0F);
      this.handelbarR = new ModelRenderer(this, 78, 5);
      this.handelbarR.addBox(-5.0F, -3.5F, -0.5F, 3, 1, 1);
      this.handelbarR.setTextureSize(128, 64);
      this.handelbarR.mirror = true;
      this.setRotation(this.handelbarR, 0.0F, 0.0F, 0.122173F);
      this.handelbartop = new ModelRenderer(this, 70, 10);
      this.handelbartop.addBox(-2.0F, -4.0F, -1.0F, 4, 2, 2);
      this.handelbartop.setTextureSize(128, 64);
      this.handelbartop.mirror = true;
      this.setRotation(this.handelbartop, 0.0F, 0.0F, 0.0F);
      this.arm3R = new ModelRenderer(this, 70, 34);
      this.arm3R.addBox(-2.0F, 11.0F, -1.0F, 1, 2, 2);
      this.arm3R.setTextureSize(128, 64);
      this.arm3R.mirror = true;
      this.setRotation(this.arm3R, 0.0F, 0.0F, 0.0F);
      this.arm1R = new ModelRenderer(this, 70, 25);
      this.arm1R.addBox(-2.0F, 5.0F, -1.0F, 1, 4, 2);
      this.arm1R.setTextureSize(128, 64);
      this.arm1R.mirror = true;
      this.setRotation(this.arm1R, 0.0F, 0.0F, 0.0F);
      this.arm2R = new ModelRenderer(this, 70, 31);
      this.arm2R.addBox(-2.0F, 9.0F, -0.5F, 1, 2, 1);
      this.arm2R.setTextureSize(128, 64);
      this.arm2R.mirror = true;
      this.setRotation(this.arm2R, 0.0F, 0.0F, 0.0F);
      this.handelbarL = new ModelRenderer(this, 78, 5);
      this.handelbarL.mirror = true;
      this.handelbarL.addBox(2.0F, -3.5F, -0.5F, 3, 1, 1);
      this.handelbarL.setTextureSize(128, 64);
      this.setRotation(this.handelbarL, 0.0F, 0.0F, -0.122173F);
      this.handlegrip1L = new ModelRenderer(this, 70, 4);
      this.handlegrip1L.mirror = true;
      this.handlegrip1L.addBox(4.5F, -5.0F, -1.0F, 1, 3, 3);
      this.handlegrip1L.setTextureSize(128, 64);
      this.setRotation(this.handlegrip1L, 0.0F, 0.0F, 0.0F);
      this.handlegrip2L = new ModelRenderer(this, 70, 0);
      this.handlegrip2L.mirror = true;
      this.handlegrip2L.addBox(5.5F, -4.5F, -0.5F, 5, 2, 2);
      this.handlegrip2L.setTextureSize(128, 64);
      this.setRotation(this.handlegrip2L, 0.0F, 0.0F, 0.0F);
      this.breaksL = new ModelRenderer(this, 84, 0);
      this.breaksL.mirror = true;
      this.breaksL.addBox(5.0F, -2.5F, -1.5F, 4, 1, 1);
      this.breaksL.setTextureSize(128, 64);
      this.setRotation(this.breaksL, 0.1745329F, 0.0F, 0.0F);
      this.arm1L = new ModelRenderer(this, 70, 25);
      this.arm1L.mirror = true;
      this.arm1L.addBox(1.0F, 5.0F, -1.0F, 1, 4, 2);
      this.arm1L.setTextureSize(128, 64);
      this.setRotation(this.arm1L, 0.0F, 0.0F, 0.0F);
      this.arm2L = new ModelRenderer(this, 70, 31);
      this.arm2L.mirror = true;
      this.arm2L.addBox(1.0F, 9.0F, -0.5F, 1, 2, 1);
      this.arm2L.setTextureSize(128, 64);
      this.setRotation(this.arm2L, 0.0F, 0.0F, 0.0F);
      this.arm3L = new ModelRenderer(this, 70, 34);
      this.arm3L.mirror = true;
      this.arm3L.addBox(1.0F, 11.0F, -1.0F, 1, 2, 2);
      this.arm3L.setTextureSize(128, 64);
      this.setRotation(this.arm3L, 0.0F, 0.0F, 0.0F);
      this.tire1F = new ModelRenderer(this, 95, 0);
      this.tire1F.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire1F.setTextureSize(128, 64);
      this.tire1F.mirror = true;
      this.setRotation(this.tire1F, 0.0F, 0.0F, 0.0F);
      this.tire2F = new ModelRenderer(this, 95, 0);
      this.tire2F.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire2F.setTextureSize(128, 64);
      this.tire2F.mirror = true;
      this.setRotation(this.tire2F, 0.7853982F, 0.0F, 0.0F);
      this.tire3F = new ModelRenderer(this, 95, 0);
      this.tire3F.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire3F.setTextureSize(128, 64);
      this.tire3F.mirror = true;
      this.setRotation(this.tire3F, 1.570796F, 0.0F, 0.0F);
      this.tire4F = new ModelRenderer(this, 95, 0);
      this.tire4F.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire4F.setTextureSize(128, 64);
      this.tire4F.mirror = true;
      this.setRotation(this.tire4F, 2.356194F, 0.0F, 0.0F);
      this.tire5F = new ModelRenderer(this, 95, 0);
      this.tire5F.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire5F.setTextureSize(128, 64);
      this.tire5F.mirror = true;
      this.setRotation(this.tire5F, 3.141593F, 0.0F, 0.0F);
      this.tire6F = new ModelRenderer(this, 95, 0);
      this.tire6F.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire6F.setTextureSize(128, 64);
      this.tire6F.mirror = true;
      this.setRotation(this.tire6F, -2.356194F, 0.0F, 0.0F);
      this.tire7F = new ModelRenderer(this, 95, 0);
      this.tire7F.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire7F.setTextureSize(128, 64);
      this.tire7F.mirror = true;
      this.setRotation(this.tire7F, -1.570796F, 0.0F, 0.0F);
      this.tire8F = new ModelRenderer(this, 95, 0);
      this.tire8F.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire8F.setTextureSize(128, 64);
      this.tire8F.mirror = true;
      this.setRotation(this.tire8F, -0.7853982F, 0.0F, 0.0F);
      this.wheel_axelF = new ModelRenderer(this, 95, 30);
      this.wheel_axelF.addBox(-2.5F, -0.5F, -0.5F, 5, 1, 1);
      this.wheel_axelF.setRotationPoint(0.0F, 12.0F, 0.0F);
      this.wheel_axelF.setTextureSize(128, 64);
      this.wheel_axelF.mirror = true;
      this.setRotation(this.wheel_axelF, 0.0F, 0.0F, 0.0F);
      this.spokesF = new ModelRenderer(this, 95, 8);
      this.spokesF.addBox(-0.5F, -5.5F, -5.5F, 1, 11, 11);
      this.spokesF.setTextureSize(128, 64);
      this.spokesF.mirror = true;
      this.setRotation(this.spokesF, 0.0F, 0.0F, 0.0F);
      this.biggear = new ModelRenderer(this, 0, 0);
      this.biggear.addBox(-1.9F, -2.5F, -2.5F, 1, 5, 5);
      this.biggear.setRotationPoint(0.0F, 14.5F, 4.5F);
      this.biggear.setTextureSize(128, 64);
      this.biggear.mirror = true;
      this.setRotation(this.biggear, 0.0F, 0.0F, 0.0F);
      this.Shape27 = new ModelRenderer(this, 0, 43);
      this.Shape27.addBox(-3.0F, -1.0F, -1.0F, 6, 2, 2);
      this.Shape27.setRotationPoint(0.0F, 14.5F, 4.5F);
      this.Shape27.setTextureSize(128, 64);
      this.Shape27.mirror = true;
      this.setRotation(this.Shape27, 0.0F, 0.0F, 0.0F);
      this.peddlearm1 = new ModelRenderer(this, 12, 0);
      this.peddlearm1.addBox(-4.0F, -0.5F, -4.5F, 1, 1, 5);
      this.peddlearm1.setRotationPoint(0.0F, 14.5F, 4.5F);
      this.peddlearm1.setTextureSize(128, 64);
      this.peddlearm1.mirror = true;
      this.setRotation(this.peddlearm1, -2.356194F, 0.0F, 0.0F);
      this.Peddle1 = new ModelRenderer(this, 24, 0);
      this.Peddle1.addBox(-8.0F, -1.5F, -5.0F, 4, 3, 1);
      this.Peddle1.setRotationPoint(0.0F, 14.5F, 4.5F);
      this.Peddle1.setTextureSize(128, 64);
      this.Peddle1.mirror = true;
      this.setRotation(this.Peddle1, -2.356194F, 0.0F, 0.0F);
      this.peddlearm2 = new ModelRenderer(this, 12, 0);
      this.peddlearm2.mirror = true;
      this.peddlearm2.addBox(3.0F, -0.5F, -4.5F, 1, 1, 5);
      this.peddlearm2.setRotationPoint(0.0F, 14.5F, 4.5F);
      this.peddlearm2.setTextureSize(128, 64);
      this.setRotation(this.peddlearm2, 0.7853982F, 0.0F, 0.0F);
      this.Peddle2 = new ModelRenderer(this, 24, 0);
      this.Peddle2.mirror = true;
      this.Peddle2.addBox(4.0F, -1.5F, -5.0F, 4, 3, 1);
      this.Peddle2.setRotationPoint(0.0F, 14.5F, 4.5F);
      this.Peddle2.setTextureSize(128, 64);
      this.setRotation(this.Peddle2, 0.7853982F, 0.0F, 0.0F);
      this.tire1B = new ModelRenderer(this, 95, 0);
      this.tire1B.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire1B.setTextureSize(128, 64);
      this.tire1B.mirror = true;
      this.setRotation(this.tire1B, 0.0F, 0.0F, 0.0F);
      this.tire2B = new ModelRenderer(this, 95, 0);
      this.tire2B.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire2B.setTextureSize(128, 64);
      this.tire2B.mirror = true;
      this.setRotation(this.tire2B, 0.7853982F, 0.0F, 0.0F);
      this.tire3B = new ModelRenderer(this, 95, 0);
      this.tire3B.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire3B.setTextureSize(128, 64);
      this.tire3B.mirror = true;
      this.setRotation(this.tire3B, 1.570796F, 0.0F, 0.0F);
      this.tire4B = new ModelRenderer(this, 95, 0);
      this.tire4B.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire4B.setTextureSize(128, 64);
      this.tire4B.mirror = true;
      this.setRotation(this.tire4B, 2.356194F, 0.0F, 0.0F);
      this.tire5B = new ModelRenderer(this, 95, 0);
      this.tire5B.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire5B.setTextureSize(128, 64);
      this.tire5B.mirror = true;
      this.setRotation(this.tire5B, 3.141593F, 0.0F, 0.0F);
      this.tire6B = new ModelRenderer(this, 95, 0);
      this.tire6B.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire6B.setTextureSize(128, 64);
      this.tire6B.mirror = true;
      this.setRotation(this.tire6B, -2.356194F, 0.0F, 0.0F);
      this.tire7B = new ModelRenderer(this, 95, 0);
      this.tire7B.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire7B.setTextureSize(128, 64);
      this.tire7B.mirror = true;
      this.setRotation(this.tire7B, -1.570796F, 0.0F, 0.0F);
      this.tire8B = new ModelRenderer(this, 95, 0);
      this.tire8B.addBox(-1.0F, -7.0F, -3.0F, 2, 2, 6);
      this.tire8B.setTextureSize(128, 64);
      this.tire8B.mirror = true;
      this.setRotation(this.tire8B, -0.7853982F, 0.0F, 0.0F);
      this.wheel_axelB = new ModelRenderer(this, 95, 30);
      this.wheel_axelB.addBox(-2.5F, -0.5F, -0.5F, 5, 1, 1);
      this.wheel_axelB.setRotationPoint(0.0F, 15.0F, 13.0F);
      this.wheel_axelB.setTextureSize(128, 64);
      this.wheel_axelB.mirror = true;
      this.setRotation(this.wheel_axelB, 0.0F, 0.0F, 0.0F);
      this.spokesB = new ModelRenderer(this, 95, 8);
      this.spokesB.addBox(-0.5F, -5.5F, -5.5F, 1, 11, 11);
      this.spokesB.setTextureSize(128, 64);
      this.spokesB.mirror = true;
      this.setRotation(this.spokesB, 0.0F, 0.0F, 0.0F);
      this.handleAssembly = new ModelRenderer(this);
      this.handleAssembly.setRotationPoint(0.0F, 3.0F, -8.5F);
      this.handleAssembly.addChild(this.handlebarmiddle);
      this.handleAssembly.addChild(this.handleparsplit);
      this.handleAssembly.addChild(this.breaksR);
      this.handleAssembly.addChild(this.pokeballthingy);
      this.handleAssembly.addChild(this.handlegrip1R);
      this.handleAssembly.addChild(this.handlegrip2R);
      this.handleAssembly.addChild(this.handelbarR);
      this.handleAssembly.addChild(this.handelbartop);
      this.handleAssembly.addChild(this.arm3R);
      this.handleAssembly.addChild(this.arm1R);
      this.handleAssembly.addChild(this.arm2R);
      this.handleAssembly.addChild(this.handelbarL);
      this.handleAssembly.addChild(this.handlegrip1L);
      this.handleAssembly.addChild(this.handlegrip2L);
      this.handleAssembly.addChild(this.breaksL);
      this.handleAssembly.addChild(this.arm1L);
      this.handleAssembly.addChild(this.arm2L);
      this.handleAssembly.addChild(this.arm3L);
      this.handleAssembly.addChild(this.wheel_axelF);
      this.frontTire.setRotationPoint(0.0F, 12.0F, 0.0F);
      this.frontTire.addChild(this.tire2F);
      this.frontTire.addChild(this.tire3F);
      this.frontTire.addChild(this.tire4F);
      this.frontTire.addChild(this.tire5F);
      this.frontTire.addChild(this.tire6F);
      this.frontTire.addChild(this.tire7F);
      this.frontTire.addChild(this.tire8F);
      this.frontTire.addChild(this.spokesF);
      this.frontTire.addChild(this.tire1F);
      this.handleAssembly.addChild(this.frontTire);
      this.pedalAssembly = new ModelRenderer(this);
      this.pedalAssembly.setRotationPoint(this.biggear.rotationPointX, this.biggear.rotationPointY, this.biggear.rotationPointZ);
      this.pedalAssembly.addChild(this.biggear);
      this.pedalAssembly.addChild(this.peddlearm1);
      this.pedalAssembly.addChild(this.Peddle1);
      this.pedalAssembly.addChild(this.peddlearm2);
      this.pedalAssembly.addChild(this.Peddle2);
      this.rearTire.setRotationPoint(0.0F, 15.0F, 13.0F);
      this.rearTire.addChild(this.tire2B);
      this.rearTire.addChild(this.tire3B);
      this.rearTire.addChild(this.tire4B);
      this.rearTire.addChild(this.tire5B);
      this.rearTire.addChild(this.tire6B);
      this.rearTire.addChild(this.tire7B);
      this.rearTire.addChild(this.tire8B);
      this.rearTire.addChild(this.spokesB);
      this.rearTire.addChild(this.tire1B);

      ModelRenderer mr;
      for(Iterator var1 = this.pedalAssembly.childModels.iterator(); var1.hasNext(); mr.offsetZ = -0.275F) {
         mr = (ModelRenderer)var1.next();
         mr.offsetY = -0.9F;
      }

   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.frame1.render(f5);
      this.seatR.render(f5);
      this.seatF.render(f5);
      this.frame2R.render(f5);
      this.frame3.render(f5);
      this.frame4R.render(f5);
      this.frame5R.render(f5);
      this.frame6.render(f5);
      this.frame7.render(f5);
      this.frame8.render(f5);
      this.frame9.render(f5);
      this.frame10.render(f5);
      this.frame11.render(f5);
      this.frame12.render(f5);
      this.chain1.render(f5);
      this.chain2.render(f5);
      this.frame2L.render(f5);
      this.frame4L.render(f5);
      this.frame5L.render(f5);
      this.seatL.render(f5);
      this.Shape27.render(f5);
      this.wheel_axelB.render(f5);
      this.handleAssembly.render(f5);
      this.pedalAssembly.render(f5);
      this.rearTire.render(f5);
   }

   @Override
   public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity entity) {
      super.setRotationAngles(par1, par2, par3, par4, par5, par6, entity);

      // 엔티티의 이동 속도에 따른 계산
      if (entity instanceof EntityAcrobike) {
         EntityAcrobike acrobike = (EntityAcrobike) entity;

         if (acrobike.motionX != 0 || acrobike.motionZ != 0) {
            float speed = (float) Math.sqrt(acrobike.motionX * acrobike.motionX + acrobike.motionZ * acrobike.motionZ); // 속도 계산
            float wheelRotation = speed / 10F; // 바퀴 회전 속도
            float pedalRotation = speed / 10F; // 페달 회전 속도

            acrobike.wheelRotation += wheelRotation;
            acrobike.pedalRotation += pedalRotation;
         }

         // 바퀴 회전
         this.frontTire.rotateAngleX = acrobike.wheelRotation;
         this.rearTire.rotateAngleX = acrobike.wheelRotation;

         // 페달 회전
         this.peddlearm1.rotateAngleX = acrobike.pedalRotation;
         this.peddlearm2.rotateAngleX = acrobike.pedalRotation + (float) Math.PI;
         this.Peddle1.rotateAngleX = acrobike.pedalRotation;
         this.Peddle2.rotateAngleX = acrobike.pedalRotation + (float) Math.PI;

         float yawChange = acrobike.rotationYaw - acrobike.prevRotationYaw;
         this.handleAssembly.rotateAngleY = yawChange * 0.0349066F;
         this.frontTire.rotateAngleY = yawChange * 0.0349066F;
      }
   }

   private void setRotation(ModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }
}
